In [731]:
import pandas as pd

In [732]:
df = pd.read_csv('../data/processed/uber.csv')

In [733]:
pd.set_option('display.max_column', None)

## How many rides are completed?

In [735]:
df[df['status']=='Completed']['status'].count()

93000

## List all unique vehicle types.

In [737]:
df['vehicle_type'].unique()

array(['eBike', 'Go Sedan', 'Auto', 'Premier Sedan', 'Bike', 'Go Mini',
       'Uber XL'], dtype=object)

## Show details of all rides paid via "Cash".

In [739]:
df[df['pay_method']=='Cash']

,date,time,booking_id,status,customer_id,vehicle_type,pickup_location,drop_location,avg_vtat,avg_ctat,customer_cancel,customer_cancel_reason,driver_cancel,driver_cancel_reason,incomplete_rides,incomplete_rides_reason,fare_price,ride_distance,driver_rating,customer_rating,pay_method
9,2024-12-16,19:06:48,"""CNR7721892""",Incomplete,"""CID5214275""",Auto,Rohini,Adarsh Nagar,6.1,26.0,0.0,NaN,0.0,NaN,1.0,Other Issue,135.0,10.36,NaN,NaN,Cash
10,2024-06-14,16:24:12,"""CNR9070334""",Completed,"""CID6680340""",Auto,Udyog Bhawan,Dwarka Sector 21,7.7,18.9,0.0,NaN,0.0,NaN,0.0,NaN,181.0,19.84,4.2,4.9,Cash
35,2024-06-07,19:21:10,"""CNR7823292""",Completed,"""CID9377721""",Go Sedan,Nirman Vihar,Malviya Nagar,14.6,25.4,0.0,NaN,0.0,NaN,0.0,NaN,470.0,27.07,3.7,4.2,Cash
50,2024-05-04,21:26:59,"""CNR1572483""",Incomplete,"""CID6059557""",Go Mini,Rajiv Chowk,Central Secretariat,9.9,21.6,0.0,NaN,0.0,NaN,1.0,Vehicle Breakdown,1581.0,1.82,NaN,NaN,Cash
52,2024-10-03,22:20:34,"""CNR6584679""",Completed,"""CID4738537""",Go Mini,Jasola,Palam Vihar,11.2,40.7,0.0,NaN,0.0,NaN,0.0,NaN,545.0,44.70,4.3,4.3,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149962,2024-10-23,22:19:50,"""CNR8870913""",Completed,"""CID1790517""",Bike,Anand Vihar,Delhi Gate,10.9,33.9,0.0,NaN,0.0,NaN,0.0,NaN,227.0,23.82,4.3,4.2,Cash
149984,2024-01-14,15:42:15,"""CNR2761999""",Incomplete,"""CID3743304""",Go Sedan,Azadpur,Lajpat Nagar,5.9,12.8,0.0,NaN,0.0,NaN,1.0,Customer Demand,1146.0,13.96,NaN,NaN,Cash
149986,2024-03-15,17:49:46,"""CNR5247039""",Completed,"""CID6218492""",Premier Sedan,Preet Vihar,Anand Vihar ISBT,12.9,43.9,0.0,NaN,0.0,NaN,0.0,NaN,289.0,44.00,4.3,5.0,Cash
149993,2024-05-03,11:18:17,"""CNR9715958""",Completed,"""CID8835432""",Go Mini,Tughlakabad,Jama Masjid,13.2,20.1,0.0,NaN,0.0,NaN,0.0,NaN,280.0,29.89,4.1,4.7,Cash
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,0.0,NaN,0.0,NaN,0.0,NaN,852.0,15.93,3.9,4.4,Cash

## Get all rides where the fare price is greater than 500.

In [741]:
df[df['fare_price']>500]

,date,time,booking_id,status,customer_id,vehicle_type,pickup_location,drop_location,avg_vtat,avg_ctat,customer_cancel,customer_cancel_reason,driver_cancel,driver_cancel_reason,incomplete_rides,incomplete_rides_reason,fare_price,ride_distance,driver_rating,customer_rating,pay_method
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,0.0,NaN,0.0,NaN,0.0,NaN,627.0,13.58,4.9,4.9,Debit Card
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,0.0,NaN,0.0,NaN,0.0,NaN,737.0,48.21,4.1,4.3,UPI
6,2024-06-17,15:45:58,"""CNR2002539""",Completed,"""CID6800553""",Go Mini,Vaishali,Punjabi Bagh,7.1,20.4,0.0,NaN,0.0,NaN,0.0,NaN,640.0,41.24,4.0,4.1,UPI
14,2024-10-18,18:28:53,"""CNR8962232""",Completed,"""CID1789354""",Go Mini,Madipur,GTB Nagar,14.0,30.9,0.0,NaN,0.0,NaN,0.0,NaN,836.0,39.55,4.7,4.4,UPI
22,2024-02-23,11:02:45,"""CNR6178330""",Completed,"""CID7719678""",Go Mini,Tis Hazari,IMT Manesar,10.4,25.1,0.0,NaN,0.0,NaN,0.0,NaN,713.0,38.03,3.7,3.6,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149984,2024-01-14,15:42:15,"""CNR2761999""",Incomplete,"""CID3743304""",Go Sedan,Azadpur,Lajpat Nagar,5.9,12.8,0.0,NaN,0.0,NaN,1.0,Customer Demand,1146.0,13.96,NaN,NaN,Cash
149991,2024-07-13,14:47:30,"""CNR5591053""",Completed,"""CID1829616""",Auto,Karol Bagh,Vishwavidyalaya,11.2,30.8,0.0,NaN,0.0,NaN,0.0,NaN,597.0,27.91,4.2,4.3,UPI
149996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,0.0,NaN,0.0,NaN,0.0,NaN,1093.0,21.31,4.8,5.0,UPI
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,0.0,NaN,0.0,NaN,0.0,NaN,852.0,15.93,3.9,4.4,Cash
149999,2024-03-10,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,0.0,NaN,0.0,NaN,0.0,NaN,806.0,21.19,4.6,4.9,Credit Card

## Get the top 10 most expensive rides.

In [743]:
df[['booking_id', 'status', 'vehicle_type', 'fare_price']].sort_values(by='fare_price', ascending=False).head(10)

          booking_id     status vehicle_type  fare_price
7450    "CNR7954315"  Completed      Go Mini      4277.0
83506   "CNR1798489"  Completed         Bike      4228.0
2731    "CNR8487909"  Completed         Auto      4220.0
90418   "CNR5182516"  Completed         Auto      4202.0
7116    "CNR7356012"  Completed      Go Mini      4133.0
43469   "CNR8849175"  Completed      Go Mini      4109.0
21011   "CNR5553074"  Completed        eBike      4093.0
32935   "CNR8715944"  Completed     Go Sedan      4088.0
117985  "CNR7652202"  Completed         Auto      4060.0
90667   "CNR8875064"  Completed     Go Sedan      4044.0

## Retrieve all rides where the pickup location is "Cyber Hub" and payment method is "Credit Card".

In [745]:
mask = (df['pickup_location']=='Cyber Hub') & (df['pay_method']=='Credit Card')
df[mask]

,date,time,booking_id,status,customer_id,vehicle_type,pickup_location,drop_location,avg_vtat,avg_ctat,customer_cancel,customer_cancel_reason,driver_cancel,driver_cancel_reason,incomplete_rides,incomplete_rides_reason,fare_price,ride_distance,driver_rating,customer_rating,pay_method
751,2024-01-12,13:59:54,"""CNR6818363""",Completed,"""CID8095753""",Go Mini,Cyber Hub,Rajiv Chowk,7.9,44.7,0.0,NaN,0.0,NaN,0.0,NaN,170.0,31.74,4.4,4.5,Credit Card
1515,2024-01-02,11:32:21,"""CNR1794305""",Completed,"""CID5716327""",Auto,Cyber Hub,DLF City Court,12.9,25.9,0.0,NaN,0.0,NaN,0.0,NaN,161.0,21.59,4.7,4.7,Credit Card
6706,2024-10-22,13:51:10,"""CNR5779314""",Completed,"""CID2226453""",Go Sedan,Cyber Hub,Vatika Chowk,7.7,35.8,0.0,NaN,0.0,NaN,0.0,NaN,474.0,38.81,4.1,4.8,Credit Card
12324,2024-10-24,18:21:58,"""CNR1806740""",Completed,"""CID5229631""",Go Mini,Cyber Hub,Meerut,9.0,21.0,0.0,NaN,0.0,NaN,0.0,NaN,233.0,33.71,4.3,4.5,Credit Card
17436,2024-11-03,06:34:10,"""CNR8828203""",Incomplete,"""CID1206607""",Go Mini,Cyber Hub,Rajouri Garden,4.0,26.2,0.0,NaN,0.0,NaN,1.0,Customer Demand,324.0,3.24,NaN,NaN,Credit Card
20404,2024-01-30,14:17:43,"""CNR5413231""",Completed,"""CID7170949""",Bike,Cyber Hub,Kashmere Gate,10.7,18.6,0.0,NaN,0.0,NaN,0.0,NaN,192.0,12.15,4.6,4.9,Credit Card
24215,2024-10-15,09:44:46,"""CNR7453259""",Completed,"""CID8886755""",Go Mini,Cyber Hub,Chhatarpur,3.4,38.3,0.0,NaN,0.0,NaN,0.0,NaN,151.0,49.07,3.7,4.0,Credit Card
30124,2024-01-10,20:53:01,"""CNR1092789""",Completed,"""CID3896909""",Auto,Cyber Hub,Tughlakabad,2.6,41.9,0.0,NaN,0.0,NaN,0.0,NaN,811.0,2.15,4.6,4.7,Credit Card
31923,2024-11-24,17:45:42,"""CNR5772566""",Completed,"""CID2216713""",Premier Sedan,Cyber Hub,Uttam Nagar,3.0,23.4,0.0,NaN,0.0,NaN,0.0,NaN,375.0,49.57,4.3,4.0,Credit Card
32078,2024-11-27,20:28:39,"""CNR2607827""",Completed,"""CID8512157""",Go Mini,Cyber Hub,Kanhaiya Nagar,2.3,30.5,0.0,NaN,0.0,NaN,0.0,NaN,186.0,20.84,3.6,4.3,Credit Card
37859,2024-10-22,22:12:18,"""CNR2435857""",Completed,"""CID9149215""",Bike,Cyber Hub,Sikanderpur,5.5,24.2,0.0,NaN,0.0,NaN,0.0,NaN,890.0,13.15,3.8,4.8,Credit Card
38728,2024-09-03,02:17:31,"""CNR9818519""",Completed,"""CID2692369""",Premier Sedan,Cyber Hub,Gurgaon Sector 56,3.3,35.7,0.0,NaN,0.0,NaN,0.0,NaN,797.0,14.08,4.1,4.7,Credit Card
39591,2024-02-18,15:36:38,"""CNR6631276""",Completed,"""CID4931713""",Premier Sedan,Cyber Hub,Pataudi Chowk,2.8,22.0,0.0,NaN,0.0,NaN,0.0,NaN,286.0,35.85,5.0,4.8,Credit Card
41487,2024-02-08,21:43:02,"""CNR9271845""",Completed,"""CID4815968""",Auto,Cyber Hub,Nehru Place,4.3,30.2,0.0,NaN,0.0,NaN,0.0,NaN,260.0,22.75,3.9,3.0,Credit Card
42194,2024-01-29,10:36:00,"""CNR5963054""",Completed,"""CID9790917""",eBike,Cyber Hub,ITO,12.4,24.2,0.0,NaN,0.0,NaN,0.0,NaN,132.0,14.83,4.3,4.9,Credit Card
43214,2024-08-16,21:02:07,"""CNR5966581""",Completed,"""CID3771626""",Premier Sedan,Cyber Hub,Noida Extension,2.7,28.5,0.0,NaN,0.0,NaN,0.0,NaN,126.0,22.36,3.2,4.1,Credit Card
46812,2024-10-16,12:12:11,"""CNR5565882""",Completed,"""CID6651368""",eBike,Cyber Hub,Shahdara,8.1,29.9,0.0,NaN,0.0,NaN,0.0,NaN,175.0,21.46,4.1,4.8,Credit Card
48467,2024-02-08,09:12:51,"""CNR9336691""",Completed,"""CID9512404""",eBike,Cyber Hub,Karol Bagh,6.8,17.0,0.0,NaN,0.0,NaN,0.0,NaN,740.0,21.75,4.6,3.6,Credit Card
53269,2024-01-24,13:41:05,"""CNR5216490""",Completed,"""CID8401586""",Go Mini,Cyber Hub,Chhatarpur,10.3,32.5,0.0,NaN,0.0,NaN,0.0,NaN,181.0,35.87,4.1,4.8,Credit Card
54477,2024-10-29,19:47:51,"""CNR9211018""",Completed,"""CID5498315""",Go Mini,Cyber Hub,Greater Kailash,12.9,39.7,0.0,NaN,0.0,NaN,0.0,NaN,684.0,46.58,3.3,5.0,Credit Card
59397,2024-09-24,09:16:17,"""CNR5689916""",Completed,"""CID5218764""",Go Sedan,Cyber Hub,Chanakyapuri,7.0,16.3,0.0,NaN,0.0,NaN,0.0,NaN,121.0,24.49,4.1,4.9,Credit Card
59461,2024-08-21,10:29:30,"""CNR4292697""",Completed,"""CID9806362""",eBike,Cyber Hub,Golf Course Road,5.6,37.3,0.0,NaN,0.0,NaN,0.0,NaN,947.0,42.92,4.5,4.7,Credit Card
59772,2024-09-17,23:13:35,"""CNR3889163""",Completed,"""CID1222674""",Go Mini,Cyber Hub,Udyog Vihar,8.5,34.0,0.0,NaN,0.0,NaN,0.0,NaN,658.0,11.04,4.5,4.8,Credit Card
67645,2024-02-15,09:00:23,"""CNR6026640""",Completed,"""CID4959772""",Go Sedan,Cyber Hub,Paharganj,6.6,25.5,0.0,NaN,0.0,NaN,0.0,NaN,281.0,7.61,4.3,4.3,Credit Card
67774,2024-08-14,16:09:40,"""CNR4612188""",Completed,"""CID5311744""",Go Mini,Cyber Hub,Kadarpur,10.7,19.5,0.0,NaN,0.0,NaN,0.0,NaN,109.0,6.69,4.7,3.5,Credit Card
68373,2024-04-16,17:32:14,"""CNR9846986""",Completed,"""CID9513514""",Bike,Cyber Hub,Rithala,2.1,36.9,0.0,NaN,0.0,NaN,0.0,NaN,423.0,7.51,4.4,4.3,Credit Card
68583,2024-01-02,17:24:10,"""CNR1027527""",Completed,"""CID8920334""",Go Mini,Cyber Hub,Sikanderpur,10.0,20.4,0.0,NaN,0.0,NaN,0.0,NaN,609.0,21.12,4.4,3.7,Credit Card
71822,2024-10-06,19:36:41,"""CNR9619932""",Completed,"""CID7227801""",Bike,Cyber Hub,Madipur,5.9,37.7,0.0,NaN,0.0,NaN,0.0,NaN,268.0,19.32,4.3,4.3,Credit Card
72939,2024-11-10,15:40:27,"""CNR6725135""",Completed,"""CID9363524""",eBike,Cyber Hub,Patel Chowk,4.4,35.3,0.0,NaN,0.0,NaN,0.0,NaN,208.0,11.39,4.9,4.9,Credit Card
74548,2024-07-06,15:51:14,"""CNR5221560""",Completed,"""CID4530550""",Go Mini,Cyber Hub,Ambience Mall,13.2,26.0,0.0,NaN,0.0,NaN,0.0,NaN,384.0,9.91,4.4,5.0,Credit Card
74789,2024-01-20,15:20:02,"""CNR8285420""",Completed,"""CID2777874""",eBike,Cyber Hub,Chhatarpur,8.0,35.7,0.0,NaN,0.0,NaN,0.0,NaN,729.0,27.60,4.6,3.6,Credit Card
75063,2024-07-16,05:56:39,"""CNR9136794""",Completed,"""CID7667109""",Go Mini,Cyber Hub,Ramesh Nagar,12.3,16.6,0.0,NaN,0.0,NaN,0.0,NaN,499.0,16.55,3.8,4.2,Credit Card
81326,2024-06-21,16:05:24,"""CNR3674454""",Completed,"""CID7615197""",Premier Sedan,Cyber Hub,Ghaziabad,11.1,16.2,0.0,NaN,0.0,NaN,0.0,NaN,206.0,44.56,4.6,4.4,Credit Card
83756,2024-04-29,07:53:34,"""CNR1893698""",Completed,"""CID4861759""",Auto,Cyber Hub,Kalkaji,14.5,43.7,0.0,NaN,0.0,NaN,0.0,NaN,549.0,45.39,4.6,4.1,Credit Card
84801,2024-07-02,17:53:54,"""CNR4271780""",Completed,"""CID3040255""",Bike,Cyber Hub,Moti Nagar,12.9,35.3,0.0,NaN,0.0,NaN,0.0,NaN,968.0,4.22,3.7,4.9,Credit Card
96533,2024-02-19,21:08:39,"""CNR8809333""",Completed,"""CID6910691""",Go Sedan,Cyber Hub,Shastri Nagar,2.1,26.3,0.0,NaN,0.0,NaN,0.0,NaN,145.0,35.44,4.3,4.3,Credit Card
101242,2024-01-21,10:40:19,"""CNR5564946""",Completed,"""CID9114835""",Go Mini,Cyber Hub,Rithala,6.2,43.8,0.0,NaN,0.0,NaN,0.0,NaN,589.0,34.12,4.3,4.5,Credit Card
106087,2024-09-08,16:17:32,"""CNR7841014""",Completed,"""CID3306049""",Auto,Cyber Hub,DLF City Court,5.7,34.9,0.0,NaN,0.0,NaN,0.0,NaN,1571.0,9.49,3.8,3.4,Credit Card
108963,2024-11-15,21:08:34,"""CNR2389623""",Completed,"""CID3407551""",Bike,Cyber Hub,INA Market,9.2,30.4,0.0,NaN,0.0,NaN,0.0,NaN,3878.0,16.03,4.1,4.7,Credit Card
110200,2024-01-11,05:34:12,"""CNR1015614""",Completed,"""CID4237463""",Go Mini,Cyber Hub,Chandni Chowk,11.1,22.5,0.0,NaN,0.0,NaN,0.0,NaN,417.0,41.24,4.2,4.8,Credit Card
110386,2024-06-29,17:21:18,"""CNR9115010""",Completed,"""CID9442332""",Go Mini,Cyber Hub,Mandi House,5.1,16.0,0.0,NaN,0.0,NaN,0.0,NaN,1135.0,45.06,4.2,3.4,Credit Card
110845,2024-09-22,19:21:23,"""CNR6918254""",Completed,"""CID6157134""",Go Mini,Cyber Hub,Rajiv Chowk,6.5,27.5,0.0,NaN,0.0,NaN,0.0,NaN,593.0,43.82,4.3,4.7,Credit Card
114560,2024-02-24,20:41:39,"""CNR1994987""",Completed,"""CID2047787""",Auto,Cyber Hub,IGI Airport,5.1,18.6,0.0,NaN,0.0,NaN,0.0,NaN,695.0,31.13,4.2,4.6,Credit Card
128263,2024-01-20,15:10:03,"""CNR9699628""",Completed,"""CID1142187""",Auto,Cyber Hub,Vaishali,5.4,22.6,0.0,NaN,0.0,NaN,0.0,NaN,510.0,27.63,4.4,4.3,Credit Card
130621,2024-11-06,09:43:24,"""CNR9845003""",Completed,"""CID1316413""",Auto,Cyber Hub,Huda City Centre,4.7,35.7,0.0,NaN,0.0,NaN,0.0,NaN,254.0,45.98,3.8,4.3,Credit Card
131763,2024-03-12,21:37:25,"""CNR3946241""",Completed,"""CID9128990""",Auto,Cyber Hub,Ambience Mall,12.5,29.4,0.0,NaN,0.0,NaN,0.0,NaN,382.0,26.22,4.3,3.9,Credit Card
135393,2024-11-14,10:50:44,"""CNR3815913""",Completed,"""CID3733036""",Go Mini,Cyber Hub,Chhatarpur,6.1,29.0,0.0,NaN,0.0,NaN,0.0,NaN,423.0,46.24,4.3,4.1,Credit Card
137633,2024-04-09,03:58:39,"""CNR8765646""",Completed,"""CID4985940""",Go Sedan,Cyber Hub,Kashmere Gate,11.3,40.7,0.0,NaN,0.0,NaN,0.0,NaN,118.0,49.05,4.5,4.7,Credit Card
139499,2024-04-11,20:04:40,"""CNR2797242""",Completed,"""CID5542416""",Go Mini,Cyber Hub,Jhilmil,14.8,36.0,0.0,NaN,0.0,NaN,0.0,NaN,920.0,25.86,4.4,3.2,Credit Card
140480,2024-07-21,18:03:14,"""CNR9727923""",Completed,"""CID3301840""",Premier Sedan,Cyber Hub,Kanhaiya Nagar,13.3,20.9,0.0,NaN,0.0,NaN,0.0,NaN,125.0,16.92,4.4,4.3,Credit Card
143432,2024-10-11,21:25:55,"""CNR6798479""",Completed,"""CID1824606""",Auto,Cyber Hub,Yamuna Bank,4.7,33.6,0.0,NaN,0.0,NaN,0.0,NaN,874.0,9.91,4.1,4.2,Credit Card

## List all rides where driver_rating is less than customer_rating.

In [747]:
mask = (df['driver_rating']) < (df['customer_rating'])
df[mask]

,date,time,booking_id,status,customer_id,vehicle_type,pickup_location,drop_location,avg_vtat,avg_ctat,customer_cancel,customer_cancel_reason,driver_cancel,driver_cancel_reason,incomplete_rides,incomplete_rides_reason,fare_price,ride_distance,driver_rating,customer_rating,pay_method
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,0.0,NaN,0.0,NaN,0.0,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,0.0,NaN,0.0,NaN,0.0,NaN,737.0,48.21,4.1,4.3,UPI
5,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,0.0,NaN,0.0,NaN,0.0,NaN,316.0,4.85,4.1,4.6,UPI
6,2024-06-17,15:45:58,"""CNR2002539""",Completed,"""CID6800553""",Go Mini,Vaishali,Punjabi Bagh,7.1,20.4,0.0,NaN,0.0,NaN,0.0,NaN,640.0,41.24,4.0,4.1,UPI
10,2024-06-14,16:24:12,"""CNR9070334""",Completed,"""CID6680340""",Auto,Udyog Bhawan,Dwarka Sector 21,7.7,18.9,0.0,NaN,0.0,NaN,0.0,NaN,181.0,19.84,4.2,4.9,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149994,2024-06-14,16:46:53,"""CNR9572383""",Completed,"""CID2952237""",Go Mini,Akshardham,Greater Noida,8.2,30.6,0.0,NaN,0.0,NaN,0.0,NaN,388.0,10.51,4.3,4.9,UPI
149995,2024-11-11,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,0.0,NaN,0.0,NaN,0.0,NaN,475.0,40.08,3.7,4.1,Uber Wallet
149996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,0.0,NaN,0.0,NaN,0.0,NaN,1093.0,21.31,4.8,5.0,UPI
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,0.0,NaN,0.0,NaN,0.0,NaN,852.0,15.93,3.9,4.4,Cash
149999,2024-03-10,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,0.0,NaN,0.0,NaN,0.0,NaN,806.0,21.19,4.6,4.9,Credit Card

## Find the total number of bookings in the dataset.

In [749]:
df['booking_id'].count()

150000

## Calculate the average fare price for each vehicle_type.

In [751]:
df.groupby('vehicle_type')['fare_price'].mean().sort_values(ascending=False)

vehicle_type
Go Sedan         511.503385
Bike             510.200299
Premier Sedan    509.568169
Go Mini          507.684934
Auto             506.725241
eBike            503.897090
Uber XL          501.816749
Name: fare_price, dtype: float64

## Get the total fare revenue collected for each payment method.

In [753]:
df.groupby('pay_method')['fare_price'].sum().sort_values(ascending=False)

pay_method
UPI            23345101.0
Cash           12895649.0
Uber Wallet     6200898.0
Credit Card     5224025.0
Debit Card      4180510.0
Name: fare_price, dtype: float64

## Count the number of rides cancelled by customers for each cancellation reason.

In [755]:
df.groupby('customer_cancel_reason')['customer_cancel'].count().sort_values(ascending=False)

customer_cancel_reason
Wrong Address                                   2362
Change of plans                                 2353
Driver is not moving towards pickup location    2335
Driver asked to cancel                          2295
AC is not working                               1155
Name: customer_cancel, dtype: int64

## Find the average ride distance and average fare price for completed rides.

In [757]:
mask = df['status']=='Completed'

avg_ride = df.loc[mask, 'ride_distance'].mean()
avg_price = df.loc[mask, 'fare_price'].mean()

In [758]:
avg_ride, avg_price

(26.000492903225805, 508.17821505376344)

## Get the total number of rides for each date.

In [760]:
df.groupby('date')['booking_id'].count()

date
2024-01-01    414
2024-01-02    389
2024-01-03    384
2024-01-04    414
2024-01-05    416
             ...
2024-12-26    369
2024-12-27    431
2024-12-28    391
2024-12-29    417
2024-12-30    386
Name: booking_id, Length: 365, dtype: int64

## Find the busiest hour of the day for bookings.

In [762]:
# merging date and time column for full time access

df['full_time'] = df['date'] +' '+ df['time']

In [763]:
# converting to datetime 

df['full_time'] = pd.to_datetime(df['full_time'])

In [764]:
# accessing hour and bookings

hours = df['full_time'].dt.hour
booking_count = df.groupby(hours)['booking_id'].count().sort_values(ascending=False).head(1)
booking_count

full_time
18    12397
Name: booking_id, dtype: int64

## Calculate the number of rides on weekends vs weekdays.

In [766]:
def classify_days(day):
    return 'Weekend' if day >= 5 else 'Weekday'

df['day_type'] = df['full_time'].dt.weekday.apply(classify_days)

In [767]:
df.groupby('day_type')['booking_id'].count()

day_type
Weekday    107060
Weekend     42940
Name: booking_id, dtype: int64

## Find the top 3 pickup locations with the highest number of bookings.

In [769]:
df.groupby('pickup_location')['booking_id'].count().sort_values(ascending=False).head(3)

pickup_location
Khandsa            949
Barakhamba Road    946
Saket              931
Name: booking_id, dtype: int64

## For each driver rating, calculate the average fare price and ride distance.

In [771]:
df.groupby('driver_rating').agg(
    avg_price = ('fare_price', lambda x: round(x.mean(), 2)),
    avg_distance = ('ride_distance', lambda x: round(x.mean(), 2))
).reset_index()

    driver_rating  avg_price  avg_distance
0             3.0     521.87         25.41
1             3.1     519.88         26.04
2             3.2     501.75         26.31
3             3.3     506.02         26.37
4             3.4     501.17         25.58
5             3.5     509.73         26.69
6             3.6     504.72         26.26
7             3.7     504.23         25.94
8             3.8     509.75         26.02
9             3.9     511.26         26.28
10            4.0     526.09         25.88
11            4.1     500.30         25.82
12            4.2     506.56         25.92
13            4.3     510.33         26.10
14            4.4     509.85         26.15
15            4.5     509.70         25.94
16            4.6     506.78         25.86
17            4.7     508.56         25.87
18            4.8     514.20         26.18
19            4.9     507.64         25.99
20            5.0     504.47         26.03

## Get the percentage of incomplete rides compared to total rides.

In [773]:
(df['incomplete_rides'].sum() / len(df)) * 100

38.0

## Find the vehicle type with the highest average customer rating.

In [775]:
df.groupby('vehicle_type')['customer_rating'].mean().sort_values(ascending=False).head(1)

vehicle_type
Go Sedan    4.409996
Name: customer_rating, dtype: float64

## Group by vehicle_type and get average fare price, average distance, and average driver rating.

In [777]:
df.groupby('vehicle_type').agg(
    avg_price = ('fare_price', lambda x: x.mean()),
    avg_distance = ('ride_distance', lambda x: x.mean()),
    avg_driver_rating = ('driver_rating', lambda x: x.mean())
).reset_index()

    vehicle_type   avg_price  avg_distance  avg_driver_rating
0           Auto  506.725241     24.615996           4.232369
1           Bike  510.200299     24.649546           4.230056
2        Go Mini  507.684934     24.612090           4.227694
3       Go Sedan  511.503385     24.609325           4.231812
4  Premier Sedan  509.568169     24.598956           4.234865
5        Uber XL  501.816749     24.402893           4.238340
6          eBike  503.897090     24.990415           4.225614

## Group by customer_cancel_reason and count cancellations.

In [779]:
df.groupby('customer_cancel_reason').agg(
    total_cancel = ('customer_cancel', lambda x: x.count())
).reset_index()

                         customer_cancel_reason  total_cancel
0                             AC is not working          1155
1                               Change of plans          2353
2                        Driver asked to cancel          2295
3  Driver is not moving towards pickup location          2335
4                                 Wrong Address          2362